/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/sessions": {
    /** Sign In */
    post: operations["postAuthSessions"];
  };
  "/panel/sessions": {
    /** Sign Out */
    delete: operations["deletePanelSessions"];
  };
  "/panel/users": {
    /** List of users. */
    get: operations["getPanelUsers"];
    /** Creation of user. */
    post: operations["postPanelUsers"];
  };
}

export interface components {
  schemas: {
    MrAuthSessionCreateRequest: {
      session: components["schemas"]["MrAuthSessionCreateRequestSession"];
    };
    MrAuthSessionCreateRequestSession: {
      email: string;
      password: string;
    };
    MrPanelUserCreateRequest: {
      user: components["schemas"]["MrPanelUserCreateRequestUser"];
    };
    MrPanelUserCreateRequestUser: {
      email: string;
      password: string;
      passwordConfirmation: string;
    };
    MrPanelUserIndexResponse: {
      items: components["schemas"]["MrPanelUserIndexResponseItem"][];
      itemsTotalCount: number;
      perPage: number;
      page: number;
    };
    MrPanelUserIndexResponseItem: {
      id: number;
      email: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    MrPanelUserCreateResponse: {
      item: components["schemas"]["MrPanelUserCreateResponseItem"];
    };
    MrPanelUserCreateResponseItem: {
      id: number;
      email: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
  };
}

export interface operations {
  /** Sign In */
  postAuthSessions: {
    responses: {
      /** Success */
      200: unknown;
    };
    /** Create new session */
    requestBody: {
      content: {
        "application/json": components["schemas"]["MrAuthSessionCreateRequest"];
      };
    };
  };
  /** Sign Out */
  deletePanelSessions: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": { [key: string]: unknown };
        };
      };
    };
  };
  /** List of users. */
  getPanelUsers: {
    parameters: {
      query: {
        /** limit of records */
        limit?: number;
        /** pass an optional search string for looking up inventory */
        page?: number;
        /** List of used ids */
        ids?: number[];
        /** limit of records per page */
        perPage?: number;
      };
    };
    responses: {
      /** search results matching criteria */
      200: {
        content: {
          "application/json": components["schemas"]["MrPanelUserIndexResponse"];
        };
      };
    };
  };
  /** Creation of user. */
  postPanelUsers: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["MrPanelUserCreateResponse"];
        };
      };
    };
    /** Create new user */
    requestBody: {
      content: {
        "application/json": components["schemas"]["MrPanelUserCreateRequest"];
      };
    };
  };
}

export interface external {}
