name: CI Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run db:create
        env:
          NODE_ENV: test
          DATABASE_TEST_URL: postgres://postgres:postgres@localhost:5432/mr_koa_test
      - run: npm run db:migrate
        env:
          NODE_ENV: test
          DATABASE_TEST_URL: postgres://postgres:postgres@localhost:5432/mr_koa_test
      - run: npm run build:check
      - run: npm run test:coverage
        env:
          PORT: 3000
          NODE_ENV: test
          NODE_APP_TOKEN: tokengithub
          NODE_APP_SECRET: secret
          NODE_APP_GATEWAY_PARTICLE_TOKEN: token-test
          DATABASE_TEST_URL: postgres://postgres:postgres@localhost:5432/mr_koa_test
